/**
 * Quality Review types — the output contract for the QualityReviewAgent.
 *
 * These types model the 10-point evaluation from the assessment brief (Section 5),
 * structured to give both a numeric signal and a human-readable reason per check.
 *
 * WHY TWO CHECK SHAPES (QualityScoreCheck vs QualityBooleanCheck):
 *   Seven checks evaluate quality on a 1–10 scale — these are matters of degree.
 *   "How strong is the hook?" is a spectrum, and a score gives the Delivery Agent
 *   (and human reviewers) a precise signal for future improvement.
 *
 *   Three checks are binary — they cannot be partially true:
 *   - fabrication: either a claim is supported by the proof bank or it is not
 *   - length: either the script is within the 45–90 second target or it is not
 *   - structure: either the required narrative arc is present or it is not
 *   A score of 7/10 for "fabrication" would be meaningless — fabrication either
 *   exists or it doesn't. Binary checks enforce this precision.
 *
 * WHY overallDecision IS 'PASS' | 'HOLD' (not 'PASS' | 'FAIL'):
 *   A held script can be regenerated by the ScriptAgent and reviewed again.
 *   FAIL would imply the idea itself is bad — but the idea was already approved
 *   by a human. The script generation may have failed, not the underlying idea.
 *   HOLD keeps the door open for retry without re-triggering human approval.
 *
 * WHY overallDecision IS DERIVED FROM checks IN THE AGENT (not trusted from AI):
 *   The QualityReviewAgent programmatically overrides the AI's overallDecision if
 *   it contradicts any check. If any check.pass is false, the decision is HOLD —
 *   regardless of what the AI returned. This prevents subtle AI inconsistencies
 *   from allowing a failing script to be marked as passed.
 */

export type QualityDecision = 'PASS' | 'HOLD';

export interface QualityScoreCheck {
  pass: boolean;
  score: number; // 1–10
  reason: string;
}

export interface QualityBooleanCheck {
  pass: boolean;
  reason: string;
}

export interface QualityChecks {
  hookStrength: QualityScoreCheck;
  problemClarity: QualityScoreCheck;
  storyFlow: QualityScoreCheck;
  solutionAlignment: QualityScoreCheck;
  proofAccuracy: QualityScoreCheck;
  ctaAlignment: QualityScoreCheck;
  brandVoice: QualityScoreCheck;
  fabrication: QualityBooleanCheck;
  length: QualityBooleanCheck;
  structure: QualityBooleanCheck;
}

export interface QualityReview {
  id: string;
  scriptId: string;
  ideaId: string;
  pipelineRunId: string;
  overallDecision: QualityDecision;
  overallScore: number; // 0–100, AI-computed holistic score
  checks: QualityChecks;
  createdAt: Date;
}
